version: "3"
services:
  ## mysql
  #  db:
  #    container_name: mysql_database
  #    build: ./db
  #    image: mysql
  #    restart: unless-stopped
  #    environment:
  #      MYSQL_ROOT_PASSWORD: root
  #      MYSQL_DATABSE: test_db
  #      MYSQL_USER: root
  #      MYSQL_PASSWORD: root
  #    ports:
  #      - "3306:3306"
  #    volumes:
  #    - ./db/mysql_data:/var/lib/mysql
  #    - ./db/sql/:/docker-entrypoint-initdb.d/

  # Server
  my_application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
#    depends_on:
#      - my_database
